### ISSUE TITLE
User Testing: (17-03-2019)

### ISSUE THREAD

**Issue by Hadeel-Salamin** [FACK1/ReWorks#7]
Template

username:

### main pain points using application:
1.
2.
3.

### user profile:
age:
gender:
job:

### Additional observations section:

**Comment by Hadeel-Salamin** [comment]
### username: Razan Tayyem

## user profile:
age: 23
gender: female
job: developer

## observations section:
- Website title font should be changed, also why the "e" letter in "eComit" is small?

**Comment by amanshawar** [comment]
## Username:shama

## Main pain points using application:
1.Back button to start page
2.upload photo be in center
3.Back button and Export as csv need background

## User profile
age:22
gender:female
job:student

## Additional observations section:
- New technologies to use :material UL

**Comment by orjwan98** [comment]
# User's Name: Matt Davis

### user's profile: 

Occupation: Course Facilitator of the FACK1 Code Academy. 
Gender: Male.

### Main observations:
1- Maybe the upload a photo option can have the option to upload more than one photo. 
2- Brand dropdown: Can I add my own brands or should I only stick to what's on the list?
3- Thought the logout button was a "go back" button or "go home".
4- Maybe get user feedback on each individual item instead of general feedback on _all_ items. 
5- Change the last page to an info page only where it tells the user about the new upcoming features: sell on ebay or give to charity. 

### Extra points:
1- Maybe for future features like exporting to eBay we can say: sell to eBay where eComit lists it on its own. 
2- ebay style: it should be eBay instead. 
3- Add a back button from the last page to the one before it. 
4- Consider making the back button as a top-left icon. 
5- Is the app asking me how to take a good photo or telling me? (make this more clear)

**Comment by orjwan98** [comment]
# User's Name: Anam Raheem

### User's profile:

Occupation: Tech education manager.
Gender: Female.

### Main observations:
1- Link to Camera so you'd take a photo and upload it at the same time OR make it obvious that a photo already needs to be taken. 
2- Only certain brands are accepted? Can't I add my own? what if the dropdown doesn't have my item?
3- Purchase price shouldn't be a dropdown. 
4- When you go back from the photo's info, is it to change the photo chosen?
5- Logout is thought to be a home button? (Maybe make it more clear what it is?)

**Comment by orjwan98** [comment]
# User's Name: Amin Talahmeh

### User's profile:

Occupation: Web Developer.
Gender: Male.

### Main observations:
1- In the home page use less technical and formal language. Example: instead of "generate your data" maybe replace it with "get your clothes details/info". 

### Extra points: 
1- Add a button on the "upload your photo" page to go back to home/description page.
2- Add a button to go back from the last page to the one before it.

**Comment by orjwan98** [comment]
# User's Name: Sama Amro

## User's Profile:
Occupation: Web developer.
Gender: Female.

## Main Observations: 
1- Link to Camera so you'd take a photo and upload it at the same time.
